"""
Quantitative Crypto Platform (QCP) — Canonical Signal Engine.

Strategy-agnostic signal generator executing CanonicalStrategySpec contracts against
multi-timeframe candle streams with strict point-in-time alignment and no lookahead.
"""

from dataclasses import dataclass
from typing import List, Optional, Dict, Any, Tuple
import numpy as np

from platform_core.canonical_strategy_spec import CanonicalStrategySpec
from market_intelligence.primitives import Candle


@dataclass
class SignalResult:
    """Canonical signal generated by signal engine."""
    strategy_id: str
    symbol: str
    action: str              # "BUY" or "SELL"
    timestamp: int           # Timestamp of closed LTF candle confirming signal
    entry_price: float       # Close price of confirming candle (or limit price)
    stop_loss: float         # Initial protective stop
    take_profit: float       # Primary profit target
    risk_distance: float     # abs(entry_price - stop_loss)
    tp_r: float              # Target R multiple
    metadata: Dict[str, Any] # Indicator values, MTF state snapshot


def _calc_ema(prices: np.ndarray, period: int) -> np.ndarray:
    """Calculate Exponential Moving Average using standard smoothing."""
    alpha = 2.0 / (period + 1.0)
    ema = np.empty_like(prices)
    if len(prices) == 0:
        return ema
    ema[0] = prices[0]
    for i in range(1, len(prices)):
        ema[i] = alpha * prices[i] + (1.0 - alpha) * ema[i - 1]
    return ema


def _calc_atr(highs: np.ndarray, lows: np.ndarray, closes: np.ndarray, period: int = 14) -> np.ndarray:
    """Calculate Average True Range using Wilders smoothing."""
    if len(closes) < 2:
        return np.zeros_like(closes)
    tr = np.maximum(
        highs[1:] - lows[1:],
        np.maximum(
            np.abs(highs[1:] - closes[:-1]),
            np.abs(lows[1:] - closes[:-1])
        )
    )
    tr = np.concatenate(([highs[0] - lows[0]], tr))
    alpha = 1.0 / period
    atr = np.empty_like(tr)
    atr[0] = tr[0]
    for i in range(1, len(tr)):
        atr[i] = alpha * tr[i] + (1.0 - alpha) * atr[i - 1]
    return atr


def _calc_donchian(highs: np.ndarray, lows: np.ndarray, period: int) -> Tuple[np.ndarray, np.ndarray]:
    """Calculate Donchian upper/lower channels shifted by 1 bar to prevent lookahead."""
    n = len(highs)
    upper = np.zeros(n)
    lower = np.zeros(n)
    for i in range(n):
        start_idx = max(0, i - period)
        if i == 0:
            upper[i] = highs[0]
            lower[i] = lows[0]
        else:
            upper[i] = np.max(highs[start_idx:i])
            lower[i] = np.min(lows[start_idx:i])
    return upper, lower


class CanonicalSignalEngine:
    """
    Executes a CanonicalStrategySpec over closed candle series.
    Provides point-in-time multi-timeframe state synchronization.
    """

    def __init__(self, spec: CanonicalStrategySpec):
        self.spec = spec
        self.spec.validate()
        self._series_prepared = False

    def prepare_series(
        self,
        ltf_candles: List[Candle],
        mtf_candles: List[Candle],
        htf_candles: List[Candle],
    ) -> None:
        """
        Pre-computes all indicator arrays and point-in-time MTF mappings using vectorized numpy.
        Enables O(1) signal checks per bar without lookahead.
        """
        self.ltf_candles = ltf_candles
        self.mtf_candles = mtf_candles
        self.htf_candles = htf_candles

        ltf_ts = np.array([c.timestamp for c in ltf_candles], dtype=np.int64)
        ltf_c = np.array([c.close for c in ltf_candles], dtype=np.float64)
        ltf_h = np.array([c.high for c in ltf_candles], dtype=np.float64)
        ltf_l = np.array([c.low for c in ltf_candles], dtype=np.float64)

        htf_ts = np.array([c.timestamp for c in htf_candles], dtype=np.int64)
        htf_c = np.array([c.close for c in htf_candles], dtype=np.float64)

        mtf_ts = np.array([c.timestamp for c in mtf_candles], dtype=np.int64)
        mtf_c = np.array([c.close for c in mtf_candles], dtype=np.float64)

        ema_len = int(self.spec.parameters.get("ema_len", 21))
        donchian_len = int(self.spec.parameters.get("donchian_len", 10))
        atr_period = int(self.spec.parameters.get("atr_period", 14))

        htf_ema = _calc_ema(htf_c, ema_len)
        htf_bull_raw = htf_c > htf_ema
        htf_bear_raw = htf_c < htf_ema

        mtf_ema = _calc_ema(mtf_c, ema_len)
        mtf_bull_raw = mtf_c > mtf_ema
        mtf_bear_raw = mtf_c < mtf_ema

        # Point-in-time synchronization onto ltf_ts:
        # searchsorted(..., side='right') - 1 gives the highest index in htf_ts where htf_ts[i] <= ltf_ts[j]
        htf_idx = np.searchsorted(htf_ts, ltf_ts, side="right") - 1
        valid_htf = htf_idx >= 24  # Require at least 25 bars of history
        htf_idx_clamped = np.clip(htf_idx, 0, len(htf_ts) - 1)

        self._htf_bull = np.where(valid_htf, htf_bull_raw[htf_idx_clamped], False)
        self._htf_bear = np.where(valid_htf, htf_bear_raw[htf_idx_clamped], False)
        self._htf_c = htf_c[htf_idx_clamped]
        self._htf_ema = htf_ema[htf_idx_clamped]

        mtf_idx = np.searchsorted(mtf_ts, ltf_ts, side="right") - 1
        valid_mtf = mtf_idx >= 24  # Require at least 25 bars of history
        mtf_idx_clamped = np.clip(mtf_idx, 0, len(mtf_ts) - 1)

        self._mtf_bull = np.where(valid_mtf, mtf_bull_raw[mtf_idx_clamped], False)
        self._mtf_bear = np.where(valid_mtf, mtf_bear_raw[mtf_idx_clamped], False)
        self._mtf_c = mtf_c[mtf_idx_clamped]
        self._mtf_ema = mtf_ema[mtf_idx_clamped]

        self._d_upper, self._d_lower = _calc_donchian(ltf_h, ltf_l, donchian_len)
        self._atr = _calc_atr(ltf_h, ltf_l, ltf_c, atr_period)
        self._ltf_c = ltf_c
        self._ltf_ts = ltf_ts
        self._series_prepared = True

    def generate_signal_at_bar(
        self,
        ltf_candles: Optional[List[Candle]] = None,
        mtf_candles: Optional[List[Candle]] = None,
        htf_candles: Optional[List[Candle]] = None,
        bar_idx: int = -1,
    ) -> Optional[SignalResult]:
        """
        Evaluates signals on the LTF bar at bar_idx (default: latest closed candle).
        Strict point-in-time lookahead protection: Only MTF/HTF candles that closed
        at or before the target LTF bar's timestamp are visible.
        """
        if not self._series_prepared:
            if ltf_candles is None or mtf_candles is None or htf_candles is None:
                raise ValueError("Must provide candles or call prepare_series first.")
            self.prepare_series(ltf_candles, mtf_candles, htf_candles)

        if self.spec.family_id == "FAM-07-MTFCONT":
            return self._evaluate_fam07_fast(bar_idx)
        else:
            raise NotImplementedError(f"Signal engine family '{self.spec.family_id}' not yet wired.")

    def _evaluate_fam07_fast(self, bar_idx: int) -> Optional[SignalResult]:
        """Fast O(1) evaluation for Family 7 on prepared series."""
        n_ltf = len(self._ltf_c)
        idx = bar_idx if bar_idx >= 0 else n_ltf + bar_idx
        if idx < 50 or idx >= n_ltf:
            return None

        curr_ts = int(self._ltf_ts[idx])
        c_close = float(self._ltf_c[idx])
        curr_atr = float(self._atr[idx])
        atr_mult = float(self.spec.parameters.get("atr_mult", 1.5))
        tp_r = float(self.spec.parameters.get("tp_r", 2.5))
        sl_dist = curr_atr * atr_mult

        if sl_dist <= 1e-6:
            return None

        is_long = bool(self._htf_bull[idx] and self._mtf_bull[idx] and (c_close > self._d_upper[idx]))
        is_short = bool(self._htf_bear[idx] and self._mtf_bear[idx] and (c_close < self._d_lower[idx]))

        if is_long:
            sl_price = c_close - sl_dist
            tp_price = c_close + (sl_dist * tp_r)
            return SignalResult(
                strategy_id=self.spec.strategy_id,
                symbol=self.spec.symbol,
                action="BUY",
                timestamp=curr_ts,
                entry_price=c_close,
                stop_loss=round(sl_price, 4),
                take_profit=round(tp_price, 4),
                risk_distance=round(sl_dist, 4),
                tp_r=tp_r,
                metadata={
                    "htf_close": float(self._htf_c[idx]),
                    "htf_ema": round(float(self._htf_ema[idx]), 4),
                    "mtf_close": float(self._mtf_c[idx]),
                    "mtf_ema": round(float(self._mtf_ema[idx]), 4),
                    "donchian_upper": round(float(self._d_upper[idx]), 4),
                    "donchian_lower": round(float(self._d_lower[idx]), 4),
                    "atr": round(curr_atr, 4),
                }
            )
        elif is_short:
            sl_price = c_close + sl_dist
            tp_price = c_close - (sl_dist * tp_r)
            return SignalResult(
                strategy_id=self.spec.strategy_id,
                symbol=self.spec.symbol,
                action="SELL",
                timestamp=curr_ts,
                entry_price=c_close,
                stop_loss=round(sl_price, 4),
                take_profit=round(tp_price, 4),
                risk_distance=round(sl_dist, 4),
                tp_r=tp_r,
                metadata={
                    "htf_close": float(self._htf_c[idx]),
                    "htf_ema": round(float(self._htf_ema[idx]), 4),
                    "mtf_close": float(self._mtf_c[idx]),
                    "mtf_ema": round(float(self._mtf_ema[idx]), 4),
                    "donchian_upper": round(float(self._d_upper[idx]), 4),
                    "donchian_lower": round(float(self._d_lower[idx]), 4),
                    "atr": round(curr_atr, 4),
                }
            )

        return None
