"""Canonical Strategy Hypothesis Layer Contracts.

Defines the clean boundary between:
1. MARKET MODEL (What exists in the market)
2. MARKET STATE (Pure descriptive snapshot across timeframes)
3. STRATEGY HYPOTHESIS (What specific combination of observations is being tested)
4. ENTRY MODEL (How the execution is triggered on LTF)
5. TRADE MANAGEMENT (How risk, trailing, and destination targets are managed)
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

from market_model.contracts import MarketState


@dataclass
class CandidateSignal:
    """A trade candidate generated by a Strategy Hypothesis."""
    bar_index: int
    direction: int  # +1 LONG, -1 SHORT
    entry_price: float
    stop_price: float
    target_price: float
    hypothesis_id: str = "HYPOTHESIS"
    target_r: float = 4.0
    timestamp_ms: int = 0
    risk_pct: float = 0.01
    meta: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        if self.target_r == 4.0 and "target_r" in self.meta:
            self.target_r = float(self.meta["target_r"])


class StrategyHypothesis(ABC):
    """Abstract base class for all strategy hypotheses.
    
    A Strategy Hypothesis consumes purely descriptive MarketState snapshots
    from HTF, MTF, and LTF without modifying or defining the Market Model itself.
    """

    def __init__(self, hypothesis_id: str, min_target_r: float = 4.0):
        self.hypothesis_id = hypothesis_id
        self.min_target_r = min_target_r

    @abstractmethod
    def evaluate_htf(self, htf_state: MarketState) -> Optional[int]:
        """Formulate a conditional directional hypothesis from HTF MarketState.
        
        Returns:
            +1 for Long bias, -1 for Short bias, or None if no valid condition exists.
        """
        pass

    @abstractmethod
    def validate_mtf(self, mtf_state: MarketState, direction: int) -> bool:
        """Determine whether MTF price behavior validates the HTF hypothesis."""
        pass

    @abstractmethod
    def confirm_ltf_entry(
        self, ltf_state: MarketState, direction: int
    ) -> Tuple[bool, Optional[float], Optional[float]]:
        """Evaluate LTF precise confirmation and derive initial SL and TP.
        
        Returns:
            (is_confirmed, initial_sl, proposed_target)
        """
        pass
