from dataclasses import dataclass
from enum import Enum

class RiskRejectionReason(Enum):
    REJECT_RR_BELOW_FLOOR = "REJECT_RR_BELOW_FLOOR"
    REJECT_RISK_ABOVE_MAXIMUM = "REJECT_RISK_ABOVE_MAXIMUM"
    REJECT_DAILY_DRAWDOWN_LIMIT = "REJECT_DAILY_DRAWDOWN_LIMIT"
    REJECT_WEEKLY_DRAWDOWN_LIMIT = "REJECT_WEEKLY_DRAWDOWN_LIMIT"
    REJECT_SYSTEMIC_CIRCUIT_BREAKER = "REJECT_SYSTEMIC_CIRCUIT_BREAKER"
    REJECT_MAX_OPEN_POSITIONS = "REJECT_MAX_OPEN_POSITIONS"
    REJECT_MAX_ASSET_EXPOSURE = "REJECT_MAX_ASSET_EXPOSURE"
    REJECT_CORRELATED_EXPOSURE = "REJECT_CORRELATED_EXPOSURE"
    REJECT_INVALID_STOP = "REJECT_INVALID_STOP"
    REJECT_INVALID_POSITION_SIZE = "REJECT_INVALID_POSITION_SIZE"
    REJECT_NEWS_BLACKOUT = "REJECT_NEWS_BLACKOUT"
    REJECT_MIN_STOP_DISTANCE_VIOLATION = "REJECT_MIN_STOP_DISTANCE_VIOLATION"
    REJECT_ZERO_STOP_DISTANCE = "REJECT_ZERO_STOP_DISTANCE"
    REJECT_NEGATIVE_STOP_DISTANCE = "REJECT_NEGATIVE_STOP_DISTANCE"
    REJECT_MAX_NOTIONAL_VIOLATION = "REJECT_MAX_NOTIONAL_VIOLATION"
    REJECT_MAX_LEVERAGE_VIOLATION = "REJECT_MAX_LEVERAGE_VIOLATION"
    REJECT_FRICTION_ADJUSTED_RISK_VIOLATION = "REJECT_FRICTION_ADJUSTED_RISK_VIOLATION"
    REJECT_INSUFFICIENT_EQUITY = "REJECT_INSUFFICIENT_EQUITY"
    REJECT_QUANTITY_STEP_VIOLATION = "REJECT_QUANTITY_STEP_VIOLATION"

@dataclass(frozen=True)
class RiskRejectionPayload:
    """
    Telemetry artifact for trades blocked by the Risk Firewall.
    Preserves structural provenance for downstream funnel analytics.
    """
    trade_plan_id: str
    hypothesis_id: str
    symbol: str
    reason: RiskRejectionReason
    
    # Original structural metrics
    entry_price: float
    stop_loss_price: float
    target_price: float
    raw_rr: float
