"""
QCP Phase 7 — Execution OS: Order Intent & Lifecycle Contracts.
Establishes canonical contracts for the complete order lifecycle:

    Strategy Order Intent
           │
           ▼
       Risk Gate
           │
           ▼
    Execution Planner
           │
           ▼
    Smart Order Router (SOR)
           │
           ▼
      Order Manager
           │
           ▼
     Exchange Adapter
           │
           ▼
    Fill Handler & Reconciliation

All implementations are PAPER ONLY.
"""

from __future__ import annotations

import enum
import hashlib
import json
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional


class OrderIntentStatus(str, enum.Enum):
    CREATED = "CREATED"
    VALIDATED = "VALIDATED"
    RISK_APPROVED = "RISK_APPROVED"
    RISK_REJECTED = "RISK_REJECTED"
    ROUTED = "ROUTED"
    ACTIVE = "ACTIVE"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class ExecutionAlgoType(str, enum.Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    PASSIVE = "PASSIVE"
    TWAP = "TWAP"
    VWAP = "VWAP"
    ICEBERG = "ICEBERG"
    POV = "POV"
    ADAPTIVE = "ADAPTIVE"


class OrderSide(str, enum.Enum):
    BUY = "BUY"
    SELL = "SELL"


class TimeInForce(str, enum.Enum):
    GTC = "GTC"
    IOC = "IOC"
    FOK = "FOK"
    POST_ONLY = "POST_ONLY"


@dataclass
class OrderIntent:
    """
    Immutable specification of trading intention generated by a strategy.
    Contains economic parameters without binding to a specific venue or child order.
    """
    intent_id: str
    strategy_id: str
    tenant_id: str
    symbol: str
    side: OrderSide
    target_quantity: float
    urgency_level: str = "NORMAL"  # LOW, NORMAL, HIGH, EMERGENCY
    algo_type: ExecutionAlgoType = ExecutionAlgoType.LIMIT
    limit_price: Optional[float] = None
    stop_loss_price: Optional[float] = None
    take_profit_price: Optional[float] = None
    max_slippage_bps: float = 5.0
    time_horizon_sec: int = 300
    algo_params: Dict[str, Any] = field(default_factory=dict)
    created_at_utc: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def compute_hash(self) -> str:
        payload = {
            "intent_id": self.intent_id,
            "strategy_id": self.strategy_id,
            "tenant_id": self.tenant_id,
            "symbol": self.symbol,
            "side": self.side.value,
            "target_quantity": self.target_quantity,
            "created_at_utc": self.created_at_utc,
        }
        return hashlib.sha256(json.dumps(payload, sort_keys=True).encode()).hexdigest()


@dataclass
class ChildOrder:
    child_id: str
    parent_intent_id: str
    venue_id: str
    symbol: str
    side: OrderSide
    algo_type: ExecutionAlgoType
    quantity: float
    limit_price: Optional[float]
    time_in_force: TimeInForce = TimeInForce.GTC
    filled_quantity: float = 0.0
    average_fill_price: float = 0.0
    status: OrderIntentStatus = OrderIntentStatus.CREATED
    submitted_at_utc: Optional[str] = None
    last_update_utc: Optional[str] = None


@dataclass
class ExecutionFill:
    fill_id: str
    child_id: str
    parent_intent_id: str
    venue_id: str
    symbol: str
    side: OrderSide
    fill_price: float
    fill_quantity: float
    fee_usd: float
    fee_currency: str = "USDT"
    liquidity_role: str = "TAKER"  # MAKER or TAKER
    timestamp_utc: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    @property
    def notional_usd(self) -> float:
        return self.fill_price * self.fill_quantity


@dataclass
class ExecutionPlan:
    plan_id: str
    intent_id: str
    strategy_id: str
    selected_venue: str
    algo_type: ExecutionAlgoType
    total_quantity: float
    slice_count: int
    child_orders: List[ChildOrder] = field(default_factory=list)
    risk_approved: bool = False
    estimated_duration_sec: int = 60
    estimated_market_impact_bps: float = 0.0
